# Mihomo 测试配置文件
port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

proxies:
  - name: "direct"
    type: direct

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - direct

rules:
  - MATCH,PROXY